apiVersion: geartickler.com/v1alpha1
kind: AIWorkload
metadata:
  name: bert-sentiment
spec:
  modelName: bert
  modelVersion: v1
  framework: ONNX
  replicas: 3
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
      nvidia.com/gpu: "1"
    requests:
      cpu: "1"
      memory: "2Gi"
  inferenceEndpoint: /api/v1/predict
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilization: 80
    targetGPUUtilization: 80
