apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiworkloads.geartickler.com
spec:
  group: geartickler.com
  names:
    kind: AIWorkload
    listKind: AIWorkloadList
    plural: aiworkloads
    singular: aiworkload
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - modelName
                - modelVersion
              properties:
                modelName:
                  type: string
                  description: "Name of the AI model"
                modelVersion:
                  type: string
                  description: "Version of the AI model"
                framework:
                  type: string
                  description: "AI framework used (e.g., ONNX, TensorFlow)"
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                  description: "Number of replicas to run"
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      additionalProperties:
                        type: string
                    requests:
                      type: object
                      additionalProperties:
                        type: string
                inferenceEndpoint:
                  type: string
                  description: "Endpoint for model inference"
                autoscaling:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    minReplicas:
                      type: integer
                      minimum: 1
                      default: 1
                    maxReplicas:
                      type: integer
                      minimum: 1
                      default: 10
                    targetCPUUtilization:
                      type: integer
                      minimum: 1
                      maximum: 100
                      default: 80
                    targetGPUUtilization:
                      type: integer
                      minimum: 1
                      maximum: 100
                      default: 80
                    scaleUpThreshold:
                      type: integer
                      minimum: 1
                      maximum: 100
                      default: 90
                    scaleDownThreshold:
                      type: integer
                      minimum: 1
                      maximum: 100
                      default: 50
            status:
              type: object
              properties:
                phase:
                  type: string
                availableReplicas:
                  type: integer
                readyReplicas:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                lastScalingTime:
                  type: string
                currentMetrics:
                  type: object
                  properties:
                    cpuUtilization:
                      type: number
                    gpuUtilization:
                      type: number
                    memoryUtilization:
                      type: number
                    inferenceLatency:
                      type: number
                    requestsPerSecond:
                      type: number
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Available
          type: integer
          jsonPath: .status.availableReplicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
